data_dir: "/root/autodl-tmp/dataset/cifar-10"


max_epochs: 10
batch_size: 32
learning_rate: 0.001
num_workers: 1


dataloder_name: "cifar10"
train_dataset:
  mode: "train"
  name: "cifar-10-batches-bin"